map_url_to_file_name = {
  '1-ne' : '1 Ne.',
  '2-ne' : '2 Ne.',
  'jacob' : 'Jacob',
  'enos' : 'Enos',
  'jarom' : 'Jarom',
  'omni' : 'Omni',
  'w-of-m' : 'W of M',
  'mosiah' : 'Mosiah',
  'alma' : 'Alma',
  'hel' : 'Hel.',
  '3-ne' : '3 Ne.',
  '4-ne' : '4 Ne.',
  'morm' : 'Morm.',
  'ether' : 'Ether',
  'moro' : 'Moro.'
}

map_ot_url_to_file_name = {
  # Old Testament
  'gen':'Gen.',
  'ex':'Ex.',
  'lev':'Lev.',
  'num':'Num.',
  'deut':'Deut.',
  'josh':'Josh',
  'judg':'Judg.',
  'ruth':'Ruth',
  '1-sam':'1 Sam.',
  '2-sam':'2 Sam.',
  '1-kgs':'1 Kgs.',
  '2-kgs':'2 Kgs.',
  '1-chr':'1 Chr.',
  '2-chr':'2 Chr.',
  'ezra':'Ezra',
  'neh':'Neh.',
  'esth':'Esth.',
  'job':'Job',
  'ps':'Ps.',
  'prov':'Prov.',
  'eccl':'Eccl.',
  'song':'Song.',
  'isa':'Isa.',
  'jer':'Jer.',
  'lam':'Lam.',
  'ezek':'Ezek.',
  'dan':'Dan.',
  'hosea':'Hosea',
  'joel':'Joel',
  'amos':'Amos',
  'obad':'Obad.',
  'jonah':'Jonah',
  'micah':'Micah',
  'nahum':'Nahum',
  'hab':'Hab.',
  'zeph':'Zeph.',
  'hag':'Hag.',
  'zech':'Zech.',
  'mal':'Mal.',
}

map_nt_url_to_file_name = {
    'matt' : 'Matt',
    'mark' : 'Mark',
    'luke' : 'Luke',
    'john' : 'John',
    'acts' : 'Acts',
    'rom' : 'Rom.',
    '1-cor' : '1 Cor.',
    '2-cor' : '2 Cor.',
    'gal' : 'Gal.',
    'eph': 'Eph.',
    'philip' : 'Philip',
    'col' : 'Col.',
    '1-thes' : '1 Thes.',
    '2-thes' : '2 Thes.',
    '1-tim' : ' 1 Tim.',
    '2-tim' : '2 Tim',
    'titus' : 'Titus',
    'philem' : 'Philem',
    'heb' : 'Heb.',
    '1-pet' : '1 Pet.',
    '2-pet' : '2 Pet.',
    '1-jn' : '1 Jn.',
    '2-jn' : '2 Jn.',
    '3-jn' : '3 Jn.',
    'jude' : 'Jude',
    'rev' : 'Rev.'
}

# map_book_to_chapter_number = {
#   '1-ne' : 1
# }


map_book_to_chapter_number = {
  '1-ne' : 22,
  '2-ne' : 33,
  'jacob' : 7,
  'enos' : 1,
  'jarom' : 1,
  'omni' : 1,
  'w-of-m' : 1,
  'mosiah' : 29,
  'alma' : 63,
  'hel' : 16,
  '3-ne' : 30,
  '4-ne' : 1,
  'morm' : 9,
  'ether' : 15,
  'moro' : 10
}

map_ot_book_to_chapter_number = {
  'gen':50,
  'ex':40,
  'lev':27,
  'num':36,
  'deut':34,
  'josh':24,
  'judg':21,
  'ruth':4,
  '1-sam':31,
  '2-sam':24,
  '1-kgs':22,
  '2-kgs':25,
  '1-chr':29,
  '2-chr':36,
  'ezra':10,
  'neh':13,
  'esth':10,
  'job':42,
  'ps':150,
  'prov':31,
  'eccl':12,
  'song':8,
  'isa':66,
  'jer':52,
  'lam':5,
  'ezek':48,
  'dan':12,
  'hosea':14,
  'joel':3,
  'amos':9,
  'obad':1,
  'jonah':4,
  'micah':7,
  'nahum':3,
  'hab':3,
  'zeph':3,
  'hag':2,
  'zech':14,
  'mal':4,
}

map_nt_book_to_chapter_number = {
    # 'matt' : 28,
    # 'mark' : 16,
    # 'luke' :24,
    # 'john' : 21,
    # 'acts' : 28,
    # 'rom' : 16,
    # '1-cor' : 16,
    # '2-cor' : 13,
    # 'gal' : 6,
    # 'eph': 6,
    # 'philip' : 4,
    # 'col' : 4,
    # '1-thes' : 5,
    # '2-thes' : 3,
    # '1-tim' : 6,
    # '2-tim' : 4,
    # 'titus' :3,
    # 'philem' : 1,
    # 'heb' : 13,
    '1-pet' : 5,
    '2-pet' : 3,
    '1-jn' : 5,
    '2-jn' : 1,
    '3-jn' : 1,
    'jude' : 1,
    'rev' : 22
}

map_dc_book_to_chapter_number = {
    'dc' : 138
}

map_dc_url_to_file_name = {
    'dc' : 'D&C'
}